### ISSUE TITLE
Ошибка при использовании curl 

### ISSUE THREAD

**Issue by shumod** [rnixik/docker-openssl-gost#13]
Пытаюсь использовать curl и отдаёт ошибку про локальный сертификат.

При запросе openssl s_client -connect esia.gosuslugi.ru:443 ошибки:
verify error:num=20:unable to get local issuer certificate
verify error:num=21:unable to verify the first certificate

При использовании curl через php вылезает ошибка:
cURL error 60: SSL certificate problem: unable to get local issuer certificate

Причём, работало нормально и в какой-то момент перестало. В чём может быть проблема?

**Comment by rnixik** [comment]
Ошибка похожа на то, что у вашего сертификата не удается проверить цепочку сертификатов и их валидность. Убедитесь, что используемый сертификат выдан валидным публичным центром сертификации, либо вы предоставляете файл с цепочкой валидных центров сертификаций.

Если перестало работать в какой-то момент, то, возможно, у одного и сертификатов цепочки истёк срок действия.

**Comment by shumod** [comment]
Помогло добавление сертификата Минсвязи. Вероятно, старый истёк.

1. https://ca.gisca.ru/support/repository/ - отсюда берём сертификат. 
https://ca.gisca.ru/repository/4BC6DC14D97010C41A26E058AD851F81C842415A.cer

2. Переделываем его в контейнере в crt формат: openssl x509 -inform DER -in 4BC6DC14D97010C41A26E058AD851F81C842415A.cer -out minsv.crt

3. Кладём в /usr/share/ca-certificates

4. update-ca-certificates

5. Проверить корректность работы openssl s_client -CApath /etc/ssl/certs/ -connect esia.gosuslugi.ru:443

**Comment by ZAZmaster** [comment]
Хочу дополнить, что лучше класть в /usr/local/share/ca-certificates и после update-ca-certificates выполнить c_rehash
