### ISSUE TITLE
Запуск на ARM64 (Apple M1)

### ISSUE THREAD

**Issue by ghost** [rnixik/docker-openssl-gost#17]
Привет!

Есть идеи, как собрать контейнер под архитектуру ARM64 на новых макбуках?

Что пробовал:
1) указать параметр `--platform=arm64` в файле `any_gost/Dockerfile`, но
```
openssl version
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

2) указать параметр `--platform=arm64` в файле `Dockerfile` (в корне), но
```
openssl version
openssl: /usr/lib/aarch64-linux-gnu/libssl.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
openssl: /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1: version `OPENSSL_1_1_1' not found (required by openssl)
```

Спасибо!

**Comment by rnixik** [comment]
Привет!

В openssl добавляли возможность собрать под darwin64-arm. Можно попробовать что-то из этого:
https://github.com/openssl/openssl/issues/12254
https://github.com/openssl/openssl/pull/12369

Сам проверить не могу.

**Comment by ghost** [comment]
Видимо, дело не в OpenSSL, а в GOST engine..
Пробовал поставить вот этот пакет https://gist.github.com/nook-ru/e697d4748085ab6d2a76b2ac037a76c0 на убунтах под arm и x86. Под arm команда `openssl engine` не видит gost.

Спрошу в репе gost, спасибо
