### ISSUE TITLE
Update OpenSSL and fix build with stunnel

### ISSUE THREAD

**Issue by netcitylife** [rnixik/docker-openssl-gost#9]
Hi, thank you very much for the image! But there are a few issues now:

1. Current image does not build because stunnel 5.50 is unavailable for download. Stunnel version should be updated to 5.53
2. It would be great to update OpenSSL default version to 1.1.0j (current latest), it contains several important bug fixes comparing to 1.1.0g and does not have problem with gost engine loading as 1.1.0h had.

**Comment by rnixik** [comment]
I updated versions of OpenSSL to 1.1.1d, stunnel to 5.55
